### ISSUE TITLE
Unable to build image, apt-get missing

### ISSUE THREAD

**Issue by rayzorben** [4nd3r/mkosi-intune#8]
I am trying to set this up on arch, it looks like maybe this only works with debian based distros?

```
sh: line 1: /usr/bin/apt-get: No such file or directory
‣ Error: "/usr/bin/apt-get update --assume-yes" returned non-zero exit code 127.
```

**Comment by 4nd3r** [comment]
Hmm, looks like this:
https://github.com/systemd/mkosi/issues/1306

Let's dive in.

**Comment by rayzorben** [comment]
Not sure what to dive into since it sounds like they require apt on the host. 

> We now require apt on the host indeed, we'll have to update the documentation

So that makes it seem like this will only work on debian based systems :(

**Comment by 4nd3r** [comment]
I'm trying to find commit where this change was made and try to understand the reasoning. Maybe it's something we can suggest to be made configurable, maybe not.

**Comment by 4nd3r** [comment]
Yep, looks like this is the way:
https://github.com/systemd/mkosi/pull/1154#issuecomment-1230339328

**Comment by glima** [comment]
I hit that too on Fedora. Was in a hurry and never got time to dig deeper--just used an older mkosi. But yeah, that's bad.

**Comment by 4nd3r** [comment]
Well, you can create nspawn container for mkosi to build... :smirk:

**Comment by bluca** [comment]
apt is available in fedora and arch https://repology.org/project/apt/versions

**Comment by glima** [comment]
The dpkg in Fedora is too old, though, apparently--no zstd compression support, while some Jammy packages seem to use it, lol. Here I go compiling it myself.

**Comment by rayzorben** [comment]
> apt is available in fedora and arch https://repology.org/project/apt/versions

Well who would have thought? :) I installed that, and now I am getting an error on finalize, not sure 

```
‣   Running finalize script…
:-(
Traceback (most recent call last):
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 41, in <module>
    main()
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 36, in main
    run_verb(args)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 4118, in run_verb
    fork_and_wait(target)
  File "/usr/lib/python3.10/site-packages/mkosi/run.py", line 166, in fork_and_wait
    result = target()
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 4113, in target
    build_stuff(uid, gid, config)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 3439, in build_stuff
    build_image(state, manifest=manifest)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 3283, in build_image
    run_finalize_script(state)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 604, in run_finalize_script
    run([state.config.finalize_script, verb],
  File "/usr/lib/python3.10/site-packages/mkosi/run.py", line 219, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, env=env, **kwargs,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
CalledProcessError: Command '['/home/rayben/mkosi-intune/mkosi.finalize', 'final']' returned non-zero exit status 1.
```

**Comment by 4nd3r** [comment]
> `:-(`

Here.

Many assumptions are made in `mkosi.finalize`:
```
if [ -z "$SUDO_UID" ] || [ -z "$SUDO_GID" ] || [ -z "$SUDO_USER" ]
then
    echo ':-(' >&2
    exit 1
fi
```

**Comment by rayzorben** [comment]
Are these vars I have to provide? 

Also, I tried to just run `make` again and it looks like it starts the process all over which takes a long time. Is there any way of resuming at the finalize step?

**Comment by 4nd3r** [comment]
I assume that you'll run `make` as regular user and you have `sudo` installed. At least this is how I use `mkosi` and friends. `SUDO_` envvars are set if you run something with `sudo`. Take a look inside of `Makefile`.

**Comment by rayzorben** [comment]
Yes, I run make and I have sudo installed. The Makefile shows running all of those commands as sudo and I am prompted to do so when I run it.

```
➜  mkosi-intune git:(main) ✗ sudo env | grep SUDO
SUDO_COMMAND=/usr/bin/env
SUDO_USER=rayben
SUDO_UID=1000
SUDO_GID=1000
```

**Comment by 4nd3r** [comment]
Change first line of `mkosi.finalize` to `#!/bin/sh -ex` and let's see if it gives us something.

**Comment by rayzorben** [comment]
Sure, do I have to run `make` again because it starts over and takes 20-30 minutes.

**Comment by 4nd3r** [comment]
Meanwhile I discovered this change:
https://github.com/systemd/mkosi/pull/1313

`mkosi` is fast moving target and everything is broken again.

Also reprod your problem, @rayzorben. Investigating.

**Comment by 4nd3r** [comment]
Changed few things and now it works again with bleeding edge `mkosi`, at least for me.

**Comment by rayzorben** [comment]
I rebuilt mkosi from git, and recloned your repo and hitting a different error before finalize

```
W: No sandbox user '_apt' on the system, can not drop privileges
‣   Setting root password
‣   Running postinstall script…
useradd: group '1000' does not exist
‣ Error: "/root/postinst final" returned non-zero exit code 6.
```

**Comment by glima** [comment]
useradd: group '1000' does not exist -> I also hit that one, been hacking around it ever since

**Comment by rayzorben** [comment]
```
➜  mkosi-intune git:(main) id
uid=1000(rayben) gid=1000(rayben) groups=1000(rayben),966(docker),998(wheel)
```
unless this is something in the image itself?

**Comment by 4nd3r** [comment]
Because my primary group is `100(users)`, which usually exists, so no need to check if group actually exists. I wanted to improve this part for pipeline, but you got ahead of me. So, anyway, https://github.com/4nd3r/mkosi-intune/commit/33e915f4d8d1ef5ac43681ea3177ac90694838f0 should help. At least [this build](https://github.com/4nd3r/mkosi-intune/actions/runs/4150333741) is happy.

**Comment by rayzorben** [comment]
Hm, did it finish? I'm confused by the suspended

```
‣   Recording packages in manifest…
‣   Resetting machine ID
‣   Running finalize script…
‣  Unmounting image…
‣  Creating archive…
‣ Saving manifest image.manifest
‣ Compressing output file /home/rayben/mkosi-intune/mkosi.output/ubuntu~jammy/image.tar…
sudo mkdir -p /etc/systemd/nspawn /var/lib/machines
[1]  + 129960 suspended (tty output)  make
➜  mkosi-intune git:(main) 
```

**Comment by 4nd3r** [comment]
Same here. If you type `fg` you get it back, but I'm yet to figure out why it happens. Not always, but sometimes.

**Comment by rayzorben** [comment]
We are making progress at least!

```
sudo machinectl start corphost
Job for systemd-nspawn@corphost.service failed because the control process exited with error code.
See "systemctl status systemd-nspawn@corphost.service" and "journalctl -xeu systemd-nspawn@corphost.service" for details.
make: *** [Makefile:24: install] Error 1
```

**Comment by 4nd3r** [comment]
You probably don't have `pcscd` installed - remove related `BindReadOnly=` line in `/etc/systemd/nspawn/corphost.nspawn`.

**Comment by 4nd3r** [comment]
> Same here. If you type fg you get it back, but I'm yet to figure out why it happens. Not always, but sometimes.

`sudo` did it. Moved it out of `Makefile` (which is ugly way of doing things anyway) and updated README.

**Comment by glima** [comment]
```
Setting up openjdk-11-jre-headless:amd64 (11.0.18+10-0ubuntu1~22.04) ...                                                                                      
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: error: error creating symbolic link '/usr/share/man/man1/java.1.gz.dpkg-tmp': No such file or directory
dpkg: error processing package openjdk-11-jre-headless:amd64 (--configure):
 installed openjdk-11-jre-headless:amd64 package post-installation script subprocess returned error exit status 2
dpkg: dependency problems prevent configuration of openjdk-11-jre:amd64:     
 openjdk-11-jre:amd64 depends on openjdk-11-jre-headless (= 11.0.18+10-0ubuntu1~22.04); however:                  
  Package openjdk-11-jre-headless:amd64 is not configured yet.                                                                                                
                                                                               
dpkg: error processing package openjdk-11-jre:amd64 (--configure):
 dependency problems - leaving unconfigured                                                                                                                   dpkg: dependency problems prevent configuration of default-jre:                                                                                                default-jre depends on openjdk-11-jre; however:                                                                                                                Package openjdk-11-jre:amd64 is not configured yet.                                                                                                                                                                                                                                                                       
dpkg: error processing package default-jre (--configure):
 dependency problems - leaving unconfigured    
dpkg: dependency problems prevent configuration of microsoft-identity-broker:                                                                                 
 microsoft-identity-broker depends on default-jre; however:
  Package default-jre is not configured yet.
                                       
dpkg: error processing package microsoft-identity-broker (--configure):        
 dependency problems - leaving unconfigured                                    
dpkg: dependency problems prevent configuration of msalsdk-dbusclient:         
 msalsdk-dbusclient depends on microsoft-identity-broker (>= 1.2); however:
  Package microsoft-identity-broker is not configured yet.
                                                                               
dpkg: error processing package msalsdk-dbusclient (--configure):               
 dependency problems - leaving unconfigured                
dpkg: dependency problems prevent configuration of intune-portal:   
 intune-portal depends on msalsdk-dbusclient (>= 1.0); however:
  Package msalsdk-dbusclient is not configured yet.
                                                                               
dpkg: error processing package intune-portal (--configure):
 dependency problems - leaving unconfigured                    
Processing triggers for dictionaries-common (1.28.14) ...                      
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Processing triggers for dbus (1.12.20-2ubuntu4.1) ...              
Errors were encountered while processing:                          
 openjdk-11-jre-headless:amd64                                                 
 openjdk-11-jre:amd64               
 default-jre                                                                   
 microsoft-identity-broker                                                     
 msalsdk-dbusclient                   
 intune-portal                    
W: Unable to read /etc/apt/apt.conf.d/ - DirectoryExists (2: No such file or directory) 
```

are the new errors in a fresh attempt. Dumping it here before I dig deeper myself... maybe I get lucky.

**Comment by glima** [comment]
```
useradd: user 'root' already exists
‣ Error: Workspace command /root/postinst final returned non-zero exit code 9.
```

is the new error after the quick hack of

```
mkosi-intune on  wayland [$] took 26ms   ✗ tree mkosi.skeleton/
mkosi.skeleton/
├── etc
│   ├── apt
│   │   ├── sources.list.d
│   │   │   ├── microsoft-edge.list
│   │   │   └── microsoft.list
│   │   └── trusted.gpg.d
│   │       └── microsoft.gpg
│   ├── profile.d
│   │   └── environment.sh
│   └── sudoers.d
│       └── sudo
└── usr
    └── share
        └── man
            └── man1
```

(that is a packaging issue anyway). Let me dig that one now...

**Comment by glima** [comment]
`❯ _UID=$(id -u) _USER=glima sudo -E make build`

finally did go through. If that is the intended (new) usage, how about documenting it?
